spring:
  config:
    import: "classpath:env.properties"
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    hibernate:
      ddl-auto: ${DDL}
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    default-encoding: UTF-8
    host: "smtp.gmail.com"
    port: ${SSL_OR_TLS}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

security:
  key: ${USER_SECURITY_KEY}