package com.commoncoremodule.enums

import com.commoncoremodule.util.EnumCodeCompanion

enum class CountryCode(val engDef: String, val korDef: String) {
    AD("ANDORRA", "안도라"),
    AE("UNITED ARAB EMIRATES", "아랍에미리트"),
    AF("AFGHANISTAN", "아프가니스탄"),
    AG("ANTIGUA AND BARBUDA", "안티구아 바부다"),
    AI("ANGUILLA", "앙길라"),
    AL("ALBANIA", "알바니아"),
    AM("ARMENIA", "아르메니아"),
    AN("NETHERLANDS ANTILLES", "네덜란드령 안틸레스"),
    AO("ANGOLA", "앙골라"),
    AQ("ANTARCTICA", "안타티카"),
    AR("ARGENTINA", "아르헨티나"),
    AS("AMERICAN SAMOA", "아메리칸 사모아"),
    AT("AUSTRIA", "오스트리아"),
    AU("AUSTRALIA", "호주"),
    AW("ARUBA", "아루바"),
    AX("ALAND ISLANDS", "알랜드 군도"),
    AZ("AZERBAIJAN", "아제르바이잔"),
    BA("BOSNIA HERCEGOVINA", "보스니아 헤르체고비나"),
    BB("BARBADOS", "바베이도스"),
    BD("BANGLADESH", "방글라데시"),
    BE("BELGIUM", "벨기에"),
    BF("BURKINA FASO", "부르키나파소"),
    BG("BULGARIA", "불가리아"),
    BH("BAHRAIN", "바레인"),
    BI("BURUNDI", "브룬디"),
    BJ("BENIN", "베냉"),
    BL("SAINT BARTHELEMY", "세인트 바르탤르미"),
    BM("BERMUDA", "버뮤다"),
    BN("BRUNEI DARUSSALAM", "브루나이"),
    BO("BOLIVIA", "볼리비아"),
    BQ("BONAIRE", "보네르"),
    BR("BRAZIL", "브라질"),
    BS("BAHAMAS", "바하마"),
    BT("BHUTAN", "부탄"),
    BV("BOUVET ISLAND", "부베섬"),
    BW("BOTSWANA", "보츠와나"),
    BY("BELARUS", "벨라루스"),
    BZ("BELIZE", "벨리즈"),
    CA("CANADA", "캐나다"),
    CC("COCOS (KEELING) ISLANDS", "코코스 제도"),
    CD("Democratic Republic of the Congo", "콩고민주공화국"),
    CF("CENTRAL AFRICAN REPUBLIC", "중앙아프리카공화국"),
    CG("CONGO", "콩고"),
    CH("SWITZERLAND", "스위스"),
    CI("COTE D`IVOIRE", "코트디부아르"),
    CK("COOK ISLANDS", "쿡 제도"),
    CL("CHILE", "칠레"),
    CM("CAMEROON", "카메룬"),
    CN("CHINA", "중국"),
    CO("COLOMBIA", "콜롬비아"),
    CR("COSTA RICA", "코스타리카"),
    CU("CUBA", "쿠바"),
    CV("CAPE VERDE", "카보베르데"),
    CW("CURACAO", "큐라소"),
    CX("CHRISTMAS ISLAND", "크리스마스섬"),
    CY("CYPRUS", "사이프러스"),
    CZ("CZECH REPUBLIC", "체코공화국"),
    DE("GERMANY", "독일"),
    DJ("DJIBOUTI", "지부티"),
    DK("DENMARK", "덴마크"),
    DM("DOMINICA", "도미니카"),
    DO("DOMINICAN REPUBLIC", "도미니카 공화국"),
    DZ("ALGERIA", "알제리"),
    EC("ECUADOR", "에쿠아도르"),
    EE("ESTONIA", "에스토니아"),
    EG("EGYPT", "이집트"),
    EH("WESTERN SAHARA", "서사하라"),
    ER("ERITREA", "에리트레아"),
    ES("SPAIN", "스페인"),
    ET("ETHIOPIA", "이디오피아"),
    FI("FINLAND", "핀란드"),
    FJ("FIJI", "피지"),
    FK("FALKLAND ISLANDS", "포클랜드섬"),
    FM("MICRONESIA", "미크로네시아"),
    FO("FAROE ISLANDS", "페로 군도"),
    FR("FRANCE", "프랑스"),
    GA("GABON", "가봉"),
    GB("UNITED KINGDOM", "영국"),
    GD("GRENADA", "그레나다"),
    GE("GEORGIA", "조지아"),
    GF("FRENCH GUIANA", "프랑스령 기아나"),
    GG("GUERNSEY", "건지"),
    GH("GHANA", "가나"),
    GI("GIBRALTAR", "지브랄타"),
    GL("GREENLAND", "그린랜드"),
    GM("GAMBIA", "감비아"),
    GN("GUINEA", "기니"),
    GP("GUADELOUPE", "과들루프"),
    GQ("EQUATORIAL GUINEA", "적도 기니"),
    GR("GREECE", "그리스"),
    GS("SOUTH GEORGIA AND SOUTH SANDWICH LSLANDS", "사우스조지아 사우스샌드위치 제도"),
    GT("GUATEMALA", "과테말라"),
    GU("GUAM", "괌"),
    GW("GUINEA-BISSAU", "기네비쏘"),
    GY("GUYANA", "가이아나"),
    HK("HONG KONG", "홍콩"),
    HM("HEARD AND MCDONALD ISLANDS", "허드 맥도날드 군도"),
    HN("HONDURAS", "온두라스"),
    HR("CROATIA", "크로아티아"),
    HT("HAITI", "아이티"),
    HU("HUNGARY", "헝가리"),
    HW("HAWAII", "하와이"),
    ID("INDONESIA", "인도네시아"),
    IE("IRELAND", "아일랜드"),
    IL("ISRAEL", "이스라엘"),
    IM("ISLE OF MAN", "맨섬"),
    IN("INDIA", "인도"),
    IO("BRITISH INDIAN OCEAN TERRITORY", "영인도 제도"),
    IQ("IRAQ", "이라크"),
    IR("IRAN", "이란"),
    IS("ICELAND", "아이슬랜드"),
    IT("ITALY", "이탈리아"),
    JE("JERSEY", "저지"),
    JM("JAMAICA", "자메이카"),
    JO("JORDAN", "요르단"),
    JP("JAPAN", "일본"),
    KE("KENYA", "케냐"),
    KG("KYRGYZSTAN", "키르기스스탄"),
    KH("CAMBODIA", "캄보디아"),
    KI("KIRIBATI", "키리바시"),
    KM("COMOROS", "코모르"),
    KN("SAINT KITTS AND NEVIS", "세인트 키츠 네비스"),
    KP("NORTH KOREA", "북한"),
    KR("KOREA", "대한민국"),
    KV("KOSOVO", "코소보"),
    KW("KUWAIT", "쿠웨이트"),
    KY("CAYMAN ISLANDS", "케이맨섬"),
    KZ("KAZAKHSTAN", "카자흐스탄"),
    LA("LAOS", "라오스"),
    LB("LEBANON", "레바논"),
    LC("SAINT LUCIA", "세인트 루시아"),
    LI("LIECHTENSTEIN", "리히텐슈타인"),
    LK("SRI LANKA", "스리랑카"),
    LR("LIBERIA", "라이베리아"),
    LS("LESOTHO", "레소토"),
    LT("LITHUANIA", "리투아니아"),
    LU("LUXEMBOURG", "룩셈부르크"),
    LV("LATVIA", "라트비아"),
    LY("LIBYAN ARAB JAMAHIRIYA", "리비아"),
    MA("MOROCCO", "모로코"),
    MC("MONACO", "모나코"),
    MD("MOLDOVA", "몰도바"),
    ME("MONTENEGRO", "몬테네그로"),
    MF("SAINT MARTIN (FRENCH PART)", "세인트 마틴"),
    MG("MADAGASCAR", "마다가스카르"),
    MH("MARSHALL ISLANDS", "마샬군도"),
    MK("MACEDONIA", "마케도니아"),
    ML("MALI", "말리"),
    MM("MYANMAR", "미얀마"),
    MN("MONGOLIA", "몽골"),
    MO("MACAU", "마카오"),
    MP("NORTHERN MARIANA ISLANDS", "북마리아나 군도"),
    MQ("MARTINIQUE", "마르티니크"),
    MR("MAURITANIA", "모리타니"),
    MS("MONTSERRAT", "몬트세라트"),
    MT("MALTA", "말타"),
    MU("MAURITIUS", "모리셔스"),
    MV("MALDIVES", "몰디브"),
    MW("MALAWI", "말라위"),
    MX("MEXICO", "멕시코"),
    MY("MALAYSIA", "말레이시아"),
    MZ("MOZAMBIQUE", "모잠비크"),
    NA("NAMIBIA", "나미비아"),
    NC("NEW CALEDONIA", "뉴칼레도니아"),
    NE("NIGER", "니제르"),
    NF("NORFOLK ISLAND", "노퍽섬"),
    NG("NIGERIA", "나이지리아"),
    NI("NICARAGUA", "니카라과"),
    NL("NETHERLANDS", "네덜란드"),
    NO("NORWAY", "노르웨이"),
    NP("NEPAL", "네팔"),
    NR("NAURU", "나우루"),
    NT("NEUTRAL ZONE", "중립지대"),
    NU("NIUE", "니우에"),
    NZ("NEW ZEALAND", "뉴질랜드"),
    OM("OMAN", "오만"),
    PA("PANAMA", "파나마"),
    PE("PERU", "페루"),
    PF("FRENCH POLYNESIA", "프랑스령 폴리네시아"),
    PG("PAPUA NEW GUINEA", "파푸아뉴기니"),
    PH("PHILIPPINES", "필리핀"),
    PK("PAKISTAN", "파키스탄"),
    PL("POLAND", "폴란드"),
    PM("SAINT PIERRE AND MIQUELON", "세인트 피에르 미?론"),
    PN("PITCAIRN", "핏케언 군도"),
    PR("PUERTO RICO", "푸에르토리코"),
    PS("PALESTINE", "팔레스타인"),
    PT("PORTUGAL", "포르투갈"),
    PW("PALAU", "팔라우"),
    PY("PARAGUAY", "파라과이"),
    QA("QATAR", "카타르"),
    RE("REUNION", "리유니언"),
    RO("ROMANIA", "루마니아"),
    RS("SERBIA", "세르비아"),
    RU("RUSSIAN FEDERATION", "러시아"),
    RW("RWANDA", "르완다"),
    SA("SAUDI ARABIA", "사우디아라비아"),
    SB("SOLOMON ISLANDS", "솔로몬 군도"),
    SC("SEYCHELLES", "세이셸"),
    SD("SUDAN", "수단"),
    SE("SWEDEN", "스웨덴"),
    SG("SINGAPORE", "싱가포르"),
    SH("SAINT HELENA", "세인트 헬레나"),
    SI("SLOVENIA", "슬로베니아"),
    SJ("SVALBARD AND JAN MAYEN ISLANDS", "스발바르드 얀마이엔 제도"),
    SK("SLOVAKIA", "슬로바키아"),
    SL("SIERRA LEONE", "시에라리온"),
    SM("SAN MARINO", "산마리노"),
    SN("SENEGAL", "세네갈"),
    SO("SOMALIA", "소말리아"),
    SR("SURINAME", "수리남"),
    SS("SOUTH SUDAN", "남수단"),
    ST("SAO TOME AND PRINCIPE", "쌍투메 프린시페"),
    SV("EL SALVADOR", "엘살바도르"),
    SX("SINT MAARTEN (DUTCH PART)", "신트마르텐"),
    SY("SYRIAN ARAB REPUBLIC", "시리아"),
    SZ("SWAZILAND", "스와질랜드"),
    TC("TURKS AND CAICOS ISLANDS", "터크스 카이코스 제도"),
    TD("CHAD", "차드"),
    TF("FRENCH SOUTHERN TERRITORIES", "프랑스 남부지역"),
    TG("TOGO", "토고"),
    TH("THAILAND", "태국"),
    TJ("TAJIKISTAN", "타지키스탄"),
    TK("TOKELAU", "토켈라우"),
    TL("EAST TIMOR", "동티모르"),
    TM("TURKMENISTAN", "투르크메니스탄"),
    TN("TUNISIA", "튀니지"),
    TO("TONGA", "통가"),
    TR("TURKEY", "터키"),
    TT("TRINIDAD AND TOBAGO", "트리니다드토바고"),
    TV("TUVALU", "투발루"),
    TW("TAIWAN", "대만"),
    TZ("TANZANIA", "탄자니아"),
    UA("UKRAINE", "우크라이나"),
    UG("UGANDA", "우간다"),
    UM("UNITED STATES MINOR OUTLYING ISLANDS", "미국령 소군도"),
    US("UNITED STATES", "미국"),
    UY("URUGUAY", "우루과이"),
    UZ("UZBEKISTAN", "우즈베키스탄"),
    VA("VATICAN CITY STATE", "바티칸"),
    VC("SAINT VINCENT AND THE GRENADINES", "세인트 빈센트 그레나딘스"),
    VE("VENEZUELA", "베네수엘라"),
    VG("VIRGIN ISLANDS (BRITISH)", "영국령 버진아일랜드"),
    VI("VIRGIN ISLANDS (U.S.)", "미국령 버진아일랜드"),
    VN("VIET NAM", "베트남"),
    VU("VANUATU", "바누아투"),
    WF("WALLIS AND FUTUNA ISLANDS", "월리스 후트나"),
    WS("SAMOA", "사모아"),
    YE("YEMEN", "예멘"),
    YT("MAYOTTE", "마요트"),
    YU("YUGOSLAVIA", "유고슬라비아"),
    ZA("SOUTH AFRICA", "남아프리카공화국"),
    ZM("ZAMBIA", "잠비아"),
    ZR("ZAIRE", "자이르"),
    ZW("ZIMBABWE", "짐바브웨"),
    ZZ("UNKNOWN", "국적불명"),
    ;
    companion object: EnumCodeCompanion<CountryCode, String>(entries.associateBy(CountryCode::engDef))
}