spring:
  config:
    import: "file:./env.properties"
    activate:
      on-profile:
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DEV_DB_URL}${DATABASE_NAME}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: ${DB_HIKARI_MAX_LIFETIME}
      maximum-pool-size: ${DB_HIKARI_MAX_POOLSIZE}
      connection-init-sql: ${DB_HIKARI_INIT_SQL}
      validation-timeout: ${DB_HIKARI_VALIDATION_TIMEOUT}
      connection-timeout: ${DB_HIKARI_CONNECTION_TIMEOUT}
      idle-timeout: ${DB_HIKARI_IDLE_TIMEOUT}
      minimum-idle: ${DB_HIKARI_MINIMUM_IDLE}

security:
  key: ${ADMIN_SECURITY_KEY}

# TODO
server:
  port: 8081