spring:
  config:
    import: "file:./env.properties"
    activate:
      on-profile:
  sql:
    init:
      mode: always
      separator: ^
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    # TODO active profile
    url: ${DEV_DB_URL}${DATABASE_NAME}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
#    url: ${PROD_DB_URL}${DATABASE_NAME}
#    username: ${PROD_DB_USER}
#    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: ${CRON_HIKARI_MAX_LIFETIME}
      maximum-pool-size: ${CRON_HIKARI_MAX_POOLSIZE}
      connection-init-sql: ${CRON_HIKARI_INIT_SQL}
      validation-timeout: ${CRON_HIKARI_VALIDATION_TIMEOUT}
      connection-timeout: ${CRON_HIKARI_CONNECTION_TIMEOUT}
      idle-timeout: ${CRON_HIKARI_IDLE_TIMEOUT}
      minimum-idle: ${CRON_HIKARI_MINIMUM_IDLE}
  quartz:
    auto-startup: ${QUARTZ_AUTO_STARTUP}
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: ${QUARTZ_THREAD_COUNT}
            threadPriority: ${QUARTZ_THREAD_PRIORITY}
        jobStore:
          misfireThreshold: ${QUARTZ_MISFIRE_THRESHOLD}
server:
  port: 8093